/**
 * Large pool of unique romantic good-morning lines (no authors).
 * Combined with scraped messages for years of daily variety.
 */

const PET_NAMES = [
    'beautiful',
    'sweetheart',
    'love',
    'baby',
    'darling',
    'princess',
    'queen',
    'angel',
    'sunshine',
    'gorgeous',
    'cutie',
    'honey',
    'beloved',
    'my love',
    'babe',
];

const TEMPLATES = [
    (n) => `Good morning, ${n}! You are the first smile my heart looks for today.`,
    (n) => `Good morning, ${n}! I woke up grateful that the universe gave me you.`,
    (n) => `Good morning, ${n}! My day already feels softer because you exist.`,
    (n) => `Good morning, ${n}! You are my favourite reason to open my eyes.`,
    (n) => `Good morning, ${n}! I hope today loves you as much as I do.`,
    (n) => `Good morning, ${n}! You are the calm in every busy morning.`,
    (n) => `Good morning, ${n}! Missing you is my heart's way of saying I adore you.`,
    (n) => `Good morning, ${n}! May your morning be gentle and your heart feel held.`,
    (n) => `Good morning, ${n}! You make loving you the easiest beautiful thing.`,
    (n) => `Good morning, ${n}! I am yours in every sunrise and every sunset.`,
    (n) => `Good morning, ${n}! Your happiness is my quiet prayer today.`,
    (n) => `Good morning, ${n}! I fall asleep thinking of you and wake up the same way.`,
    (n) => `Good morning, ${n}! You are my home even when we are apart.`,
    (n) => `Good morning, ${n}! Sending you warmth, kisses, and endless love.`,
    (n) => `Good morning, ${n}! The day feels incomplete until I tell you I love you.`,
    (n) => `Good morning, ${n}! You are the dream I never want to wake from.`,
    (n) => `Good morning, ${n}! My heart chose you and keeps choosing you.`,
    (n) => `Good morning, ${n}! You deserve a morning as lovely as your soul.`,
    (n) => `Good morning, ${n}! I am lucky to love someone as wonderful as you.`,
    (n) => `Good morning, ${n}! Today I am cheering for you louder than the sunrise.`,
    (n) => `Good morning, ${n}! You are my peace, my passion, and my joy.`,
    (n) => `Good morning, ${n}! Wrapped in thoughts of you since the first light.`,
    (n) => `Good morning, ${n}! You are the sweetest chapter of my life.`,
    (n) => `Good morning, ${n}! I hope you feel cherished from head to heart.`,
    (n) => `Good morning, ${n}! Every morning with you in my heart feels like a gift.`,
    (n) => `Good morning, ${n}! You are my always and my favourite hello.`,
    (n) => `Good morning, ${n}! May today bring you little moments of magic.`,
    (n) => `Good morning, ${n}! I adore the way you make ordinary days extraordinary.`,
    (n) => `Good morning, ${n}! You are the light my mornings were waiting for.`,
    (n) => `Good morning, ${n}! Loving you feels like breathing — natural and necessary.`,
    (n) => `Good morning, ${n}! You are my soft place in a loud world.`,
    (n) => `Good morning, ${n}! Hope your coffee is warm and your heart feels loved.`,
    (n) => `Good morning, ${n}! You are the most beautiful part of my every day.`,
    (n) => `Good morning, ${n}! I am thinking of you with the tenderest love.`,
    (n) => `Good morning, ${n}! You make my world gentler just by being in it.`,
    (n) => `Good morning, ${n}! Today I choose you again, happily and completely.`,
    (n) => `Good morning, ${n}! Your love is the melody my morning hums.`,
    (n) => `Good morning, ${n}! I hope you know how deeply you are treasured.`,
    (n) => `Good morning, ${n}! You are my favourite notification in this life.`,
    (n) => `Good morning, ${n}! May your day be kissed with joy and sweetness.`,
    (n) => `Good morning, ${n}! You are the reason my heart knows hope.`,
    (n) => `Good morning, ${n}! I love you more than yesterday, less than tomorrow.`,
    (n) => `Good morning, ${n}! You are my sunshine on cloudy mornings too.`,
    (n) => `Good morning, ${n}! Wishing you a day as beautiful as your heart.`,
    (n) => `Good morning, ${n}! You are the love story I never want to end.`,
    (n) => `Good morning, ${n}! My arms may be empty but my heart is full of you.`,
    (n) => `Good morning, ${n}! You are worth every soft word and every warm thought.`,
    (n) => `Good morning, ${n}! I hope today wraps you in love and laughter.`,
    (n) => `Good morning, ${n}! You are my forever favourite person.`,
    (n) => `Good morning, ${n}! Just wanted you to start the day feeling adored.`,
];

const STANDALONE = [
    'Good morning, my love! You are the first thought that colours my whole day.',
    'Good morning, beautiful! I hope you feel how deeply you are loved today.',
    'Good morning, sweetheart! My heart is right beside yours even from far away.',
    'Good morning, darling! You make every sunrise feel like it was made for us.',
    'Good morning, princess! Today the world is lucky to have you in it.',
    'Good morning, angel! I am grateful for you with every breath I take.',
    'Good morning, gorgeous! You are my favourite place to land.',
    'Good morning, baby! May your morning be soft, sweet, and full of love.',
    'Good morning, my queen! You deserve all the tenderness this day can give.',
    'Good morning, sunshine! I love you more with every new light.',
    'Good morning, cutie! You are the warmth my coldest mornings needed.',
    'Good morning, honey! I am yours today and every day after.',
    'Good morning, beloved! You are the peace my soul was searching for.',
    'Good morning, babe! Hope you wake up smiling because you are so loved.',
    'Good morning, my girl! You are the most beautiful blessing in my life.',
    'Good morning, love! Sending you a hug woven with all my affection.',
    'Good morning, sweetheart! You are the reason my heart knows joy.',
    'Good morning, beautiful soul! I adore you in ways words barely hold.',
    'Good morning, darling! Today I am holding you in every quiet thought.',
    'Good morning, my heart! You are my favourite miracle.',
    'Good morning, love! The best part of morning is knowing you are mine.',
    'Good morning, princess! May your day feel as lovely as your laugh.',
    'Good morning, angel face! I love you endlessly and without pause.',
    'Good morning, gorgeous! You are my dream walking in daylight.',
    'Good morning, baby girl! You make loving you feel like coming home.',
    'Good morning, sweetheart! I hope today treats you as gently as you deserve.',
    'Good morning, my love! You are the poem my heart keeps writing.',
    'Good morning, beautiful! Every day with you in my heart feels like a gift.',
    'Good morning, darling! I am thinking of you with the softest love.',
    'Good morning, sunshine! You light up my life brighter than dawn.',
    'Good morning, babe! You are cherished more than you know.',
    'Good morning, honey! My favourite hello is always you.',
    'Good morning, cutie! You are my calm, my fire, and my forever.',
    'Good morning, beloved! I hope you feel kissed by love all day.',
    'Good morning, my queen! You are adored beyond measure.',
    'Good morning, love! Waking up grateful you chose me too.',
    'Good morning, princess! You are the sparkle in my ordinary days.',
    'Good morning, angel! I love you in the quiet and the loud moments.',
    'Good morning, sweetheart! You are my always, my now, my everything.',
    'Good morning, beautiful! May today gift you peace and sweet surprises.',
];

export function generateRomanticMorningPool() {
    const pool = new Set(STANDALONE);
    for (const template of TEMPLATES) {
        for (const name of PET_NAMES) {
            pool.add(template(name));
        }
    }
    return [...pool];
}
